import type { Metadata } from "next";
import { Inter, Noto_Serif_Malayalam } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const notoMalayalam = Noto_Serif_Malayalam({
  subsets: ["malayalam", "latin"],
  weight: ["400", "600", "700"],
  variable: "--font-malayalam",
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL("https://kathalokam.vercel.app"),
  title: {
    default: "കഥാലോകം — സൗജന്യ മലയാളം ഓഡിയോ കഥകൾ",
    template: "%s | കഥാലോകം",
  },
  verification: {
    google: "hkHmi_ipunb7E6txY67bZ6Gf9y6W3RHN7BVNSw8c0zk",
  },
  description:
    "Listen to free Malayalam audio stories generated by AI. Thrillers, romance, mystery and more — completely free, no subscription needed.",
  keywords: [
    "malayalam audio stories",
    "free",
    "കഥ",
    "ഓഡിയോ കഥ",
    "kerala audiobooks",
    "malayalam stories online",
  ],
  authors: [{ name: "Kathalokam" }],
  creator: "Kathalokam",
  openGraph: {
    type: "website",
    locale: "ml_IN",
    url: "https://kathalokam.vercel.app",
    title: "കഥാലോകം — സൗജന്യ മലയാളം ഓഡിയോ കഥകൾ",
    description:
      "Listen to free Malayalam audio stories generated by AI. Thrillers, romance, mystery and more — completely free, no subscription needed.",
    siteName: "കഥാലോകം",
    images: [{ url: "/og-image.png", width: 1200, height: 630, alt: "കഥാലോകം Malayalam Audio Stories" }],
  },
  twitter: {
    card: "summary_large_image",
    title: "കഥാലോകം — സൗജന്യ മലയാളം ഓഡിയോ കഥകൾ",
    description: "Listen to free Malayalam audio stories generated by AI.",
    images: ["/og-image.png"],
  },
  icons: {
    icon: "data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>📖</text></svg>",
  },
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="ml" className={`${inter.variable} ${notoMalayalam.variable}`}>
      <body className="font-sans bg-[#080C18] text-[#F0F0FF] antialiased selection:bg-purple-500/30">
        {children}
      </body>
    </html>
  );
}
