'use client'

import React, { useState, useEffect, useMemo } from 'react'
import Link from 'next/link'
import { createClient } from '@/lib/supabase/client'
import {
  Play,
  Loader2,
  Headphones,
  Sparkles,
  BookOpen,
  AlertCircle
} from 'lucide-react'

interface Story {
  id: string
  title_malayalam: string
  title_english: string
  genre: string
  description: string
  cover_emoji: string
  total_episodes: number
  status: string
  published_at: string
}

const GENRES = [
  'All',
  'Thriller',
  'Romance',
  'Mystery',
  'Comedy',
  'Drama',
  'Horror',
  'Fantasy',
]

// Subtle earthy background tints for emoji cover art circles
const EMOJI_BG_COLORS = [
  'bg-[#1B4332]/10 border-[#1B4332]/20',
  'bg-[#D4A017]/15 border-[#D4A017]/30',
  'bg-emerald-900/10 border-emerald-900/20',
  'bg-amber-900/10 border-amber-900/20',
]

export default function HomePage() {
  const [stories, setStories] = useState<Story[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [selectedGenre, setSelectedGenre] = useState('All')

  const supabase = createClient()

  useEffect(() => {
    const fetchPublishedStories = async () => {
      try {
        setLoading(true)
        const { data, error: fetchError } = await supabase
          .from('stories')
          .select('*')
          .eq('status', 'published')
          .order('published_at', { ascending: false })

        if (fetchError) {
          throw new Error(fetchError.message)
        }

        setStories(data || [])
      } catch (err: any) {
        setError(err.message || 'കഥകൾ ലഭ്യമാക്കുന്നതിൽ പരാജയപ്പെട്ടു (Failed to load stories).')
      } finally {
        setLoading(false)
      }
    }

    fetchPublishedStories()
  }, [])

  // Client-side genre filtering
  const filteredStories = useMemo(() => {
    if (selectedGenre === 'All') return stories
    return stories.filter(
      (story) => story.genre.toLowerCase() === selectedGenre.toLowerCase()
    )
  }, [stories, selectedGenre])

  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    name: 'കഥാലോകം (Kathalokam)',
    alternateName: 'Free Malayalam Audio Stories',
    url: 'https://kathalokam.vercel.app',
    description: 'Listen to free Malayalam audio stories generated by AI. Thrillers, romance, mystery and more.',
    inLanguage: 'ml',
    potentialAction: {
      '@type': 'SearchAction',
      target: {
        '@type': 'EntryPoint',
        urlTemplate: 'https://kathalokam.vercel.app/?genre={search_term_string}',
      },
      'query-input': 'required name=search_term_string',
    },
  }

  return (
    <div className="min-h-screen flex flex-col justify-between font-serif bg-[#FDF6EC] text-[#1B4332]">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />

      {/* --- HEADER --- */}
      <header className="border-b border-[#1B4332]/15 bg-[#FDF6EC]/80 backdrop-blur-md sticky top-0 z-50">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-5 flex flex-col sm:flex-row items-center justify-between gap-3 text-center sm:text-left">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-full bg-[#1B4332] text-[#D4A017] flex items-center justify-center shadow-md">
              <Headphones className="h-5 w-5" />
            </div>
            <div>
              <h1 className="text-3xl sm:text-4xl font-bold tracking-tight font-[family-name:var(--font-malayalam)] text-[#1B4332]">
                കഥാലോകം
              </h1>
            </div>
          </div>

          <div className="flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-[#1B4332]/5 border border-[#1B4332]/15">
            <Sparkles className="h-4 w-4 text-[#D4A017] animate-pulse" />
            <span className="text-sm font-semibold font-[family-name:var(--font-malayalam)] tracking-wide text-[#1B4332]">
              സൗജന്യ മലയാളം ഓഡിയോ കഥകൾ
            </span>
          </div>
        </div>
      </header>

      {/* --- MAIN CONTENT --- */}
      <main className="flex-1 max-w-6xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8">

        {/* Genre Filter Bar (Horizontal Scroll on Mobile) */}
        <div className="relative">
          <div className="flex items-center gap-2 overflow-x-auto pb-3 pt-1 scrollbar-none no-scrollbar snap-x">
            {GENRES.map((genre) => {
              const isSelected = selectedGenre === genre
              return (
                <button
                  key={genre}
                  onClick={() => setSelectedGenre(genre)}
                  className={`px-4 py-2 rounded-full text-xs sm:text-sm font-sans font-semibold tracking-wide transition-all duration-200 whitespace-nowrap flex-shrink-0 snap-start shadow-sm ${isSelected
                    ? 'bg-[#1B4332] text-[#FDF6EC] shadow-md scale-105 border-2 border-[#1B4332]'
                    : 'bg-white/80 hover:bg-white text-[#1B4332]/80 hover:text-[#1B4332] border border-[#1B4332]/15'
                    }`}
                >
                  {genre === 'All' ? 'എല്ലാം (All)' : genre}
                </button>
              )
            })}
          </div>
        </div>

        {/* Loading Spinner */}
        {loading && (
          <div className="py-24 flex flex-col items-center justify-center gap-4 text-center">
            <Loader2 className="h-10 w-10 animate-spin text-[#1B4332]" />
            <p className="text-base font-semibold font-[family-name:var(--font-malayalam)] text-[#1B4332]/80">
              കഥകൾ ലോഡ് ചെയ്യുന്നു...
            </p>
          </div>
        )}

        {/* Error State */}
        {error && !loading && (
          <div className="max-w-md mx-auto my-12 p-6 bg-red-50 border border-red-200 rounded-2xl text-center text-red-800 font-sans shadow-sm">
            <AlertCircle className="h-8 w-8 mx-auto mb-2 text-red-600" />
            <p className="text-sm font-semibold">{error}</p>
            <button
              onClick={() => window.location.reload()}
              className="mt-4 px-4 py-2 bg-[#1B4332] text-[#FDF6EC] text-xs font-semibold rounded-lg hover:bg-[#1B4332]/90 transition"
            >
              വീണ്ടും ശ്രമിക്കുക (Retry)
            </button>
          </div>
        )}

        {/* Empty State */}
        {!loading && !error && filteredStories.length === 0 && (
          <div className="py-20 text-center space-y-3 font-sans">
            <div className="w-16 h-16 bg-[#1B4332]/5 rounded-full flex items-center justify-center mx-auto text-[#1B4332]/40">
              <BookOpen className="h-8 w-8" />
            </div>
            <h3 className="text-lg font-bold font-[family-name:var(--font-malayalam)] text-[#1B4332]">
              കഥകൾ ഒന്നും ലഭ്യമല്ല
            </h3>
            <p className="text-xs text-[#1B4332]/60 max-w-sm mx-auto">
              No published stories found in the "{selectedGenre}" category yet. Check back soon!
            </p>
          </div>
        )}

        {/* Stories Grid (2 Cols Mobile, 3 Cols Desktop) */}
        {!loading && !error && filteredStories.length > 0 && (
          <div className="grid grid-cols-2 md:grid-cols-3 gap-4 sm:gap-6">
            {filteredStories.map((story, index) => {
              const badgeColor = EMOJI_BG_COLORS[index % EMOJI_BG_COLORS.length]

              return (
                <div
                  key={story.id}
                  className="bg-white/90 hover:bg-white rounded-2xl p-4 sm:p-6 border border-[#1B4332]/15 shadow-sm hover:shadow-md transition-all duration-300 flex flex-col justify-between group"
                >
                  <div>
                    {/* Top Row: Emoji Art + Free Badge */}
                    <div className="flex items-start justify-between gap-2 mb-4">
                      <div className={`w-14 h-14 sm:w-16 sm:h-16 rounded-full flex items-center justify-center text-2xl sm:text-3xl border shadow-inner ${badgeColor}`}>
                        <span className="transform group-hover:scale-110 transition-transform duration-200">
                          {story.cover_emoji || '📖'}
                        </span>
                      </div>

                      <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-[10px] sm:text-xs font-sans font-bold bg-[#1B4332] text-[#D4A017] uppercase tracking-wider shadow-sm">
                        Free
                      </span>
                    </div>

                    {/* Titles */}
                    <div className="space-y-1 mb-4">
                      <h2 className="text-lg sm:text-xl font-bold font-[family-name:var(--font-malayalam)] leading-snug text-[#1B4332] group-hover:text-[#D4A017] transition-colors line-clamp-2">
                        {story.title_malayalam}
                      </h2>
                      {story.title_english && (
                        <p className="text-xs font-sans font-medium text-[#1B4332]/60 line-clamp-1 italic">
                          {story.title_english}
                        </p>
                      )}
                    </div>
                  </div>

                  {/* Bottom Row: Metadata + Action Button */}
                  <div className="pt-3 border-t border-[#1B4332]/10 flex items-center justify-between gap-2 font-sans">
                    <div className="flex flex-col">
                      <span className="text-[10px] font-bold uppercase tracking-wider text-[#D4A017]">
                        {story.genre}
                      </span>
                      <span className="text-xs font-semibold text-[#1B4332]/80">
                        {story.total_episodes} {story.total_episodes === 1 ? 'episode' : 'episodes'}
                      </span>
                    </div>

                    <Link
                      href={`/story/${story.id}`}
                      aria-label={`Play ${story.title_english || story.title_malayalam}`}
                      className="w-10 h-10 sm:w-11 sm:h-11 rounded-full bg-[#1B4332] hover:bg-[#1B4332]/90 text-[#FDF6EC] hover:text-[#D4A017] flex items-center justify-center shadow-md hover:scale-105 transition-all duration-200 flex-shrink-0"
                    >
                      <Play className="h-4 w-4 sm:h-5 sm:w-5 fill-current ml-0.5" />
                    </Link>
                  </div>
                </div>
              )
            })}
          </div>
        )}

      </main>

      {/* --- FOOTER --- */}
      <footer className="border-t border-[#1B4332]/15 bg-[#FDF6EC] py-8 mt-12">
        <div className="max-w-6xl mx-auto px-4 text-center font-sans">
          <p className="text-xs sm:text-sm font-semibold text-[#1B4332]/70 tracking-wide">
            കഥാലോകം · Malayalam AI Stories · 100% Free · No ads
          </p>
          <p className="text-[10px] text-[#1B4332]/40 mt-1">
            Built for Malayalam literature lovers everywhere.
          </p>
        </div>
      </footer>

    </div>
  )
}